version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
      - "9929:9929"
      - "9230:9230"
    environment:
      - NODE_ENV=development
